markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : Anup Jadhav
production_url : http://anupjadhav.com
description: "Thoughts, Ideas, Comments and other things by Anup T Jadhav."
disqus_shortname: anupj
analytics: UA-17629471-1
author :
  name : Anup T Jadhav
  github : anupj
  twitter : anup
  email: anup.jadhav@gmail.com
